#define TEXTFILE        256
#define IDR_PRE_LAUNCH_SCRIPT  101
#define IDR_STARTUP_SCRIPT  120
#define IDR_CONFIG_JSON  130
#define IDR_SHELL_SCRIPT  140
#define IDR_DOCTOR_SCRIPT  150
#define IDR_INITDB_SCRIPT  160
